import image1 from "./src/image1.jpg";
import image2 from "./src/image2.jpg";
import image3 from "./src/image3.jpg";
import image4 from "./src/image4.jpg";
import team from "./src/team.jpg";
import donation_pic from "./src/donation.jpg";
import choose1 from "../about/src/whyus-1.png";
import choose2 from "../about/src/whyus-2.png";
import choose3 from "../about/src/whyus-3.png";
import choose4 from "../about/src/whyus-4.png";
import choose5 from "../about/src/whyus5.png";

export const slider = [
  {
    id: 1,
    image: image1,
    title: "Everest Base Camp",
    quote:
      "We provide services regarding mountain expedition, peak climbing, camping and lodge trekking or any kind of activities related with this field.",
  },
  {
    id: 2,
    image: image2,
    title: "Let us help you to make your trip better",
    quote:
      "We provide services regarding mountain expedition, peak climbing, camping and lodge trekking or any kind of activities related with this field.",
  },
  {
    id: 3,
    image: image3,
    title: "Let's go to the top of the world together",
    quote:
      "We provide services regarding mountain expedition, peak climbing, camping and lodge trekking or any kind of activities related with this field.",
  },
  {
    id: 4,
    image: image4,
    title: "We Can do everything for you - Trekking, Tours and so on.",
    quote:
      "We provide services regarding mountain expedition, peak climbing, camping and lodge trekking or any kind of activities related with this field.",
  },
];

export const aboutCompany = {
  id: 1,
  image: image1,
  title: "Namaste and warm greetings from Iceland Trekking & Expedition",
  description:
    "Iceland Trekking & Expedition (P) ltd. wishes you all good health, happiness, and strength to overcome this unprecedented time of the global pandemic.We have organized Mt. Everest expedition and Mt. Lhotse expedition in spring 2021. Likewise Mera peak, Labuche peak, and Island peak expeditions were all completed successfully in 2021 but, due to the unfortunate occurrence of the second wave of the pandemic during the spring season of 2021, Mt. Everest and Mt. Lhotse expeditions had to be stopped even though all the climbing members had completed the acclimatization process.",
  descriptionSecond:
    "After the second wave subsided, we have organized the Manaslu expedition, Dhaulagiri vii expedition, and Amadablam expedition successfully, in autumn 2021. Mera peak expedition was successfully organized and accomplished in the end of autumn 2021.All expeditions, treks, and tours including the international Everest expedition will continue operating in spring 2022.We want to assure all our trekking & expedition clients, that Iceland Trekking and Expedition is prepared to start all regular activities in upcoming 2022. We hope that the ongoing pandemic will overcome through a collective global effort. Despite all uncertainty and anxiety that every one of us are facing, we remain firm in the belief that hope must be kept alive. Stay safe and healthy.",
};

export const aboutTeam = {
  id: 1,
  image: team,
  title: "About Team",
  description:
    "After more than fifteen years of experience in trekking and mountain expedition, Tendy Sherpa founded Iceland Trekking & Expedition in 1994 as a company that provided services on tours, trekking, and mountain expedition in Nepal, Bhutan, Tibet, and Pakistan.We provide the best camping equipment, fresh and hygienic foods. Our staffs are leading experts in their field with each of them having decades of experience. Each member of our team is determined and dedicated to make sure that you have a pleasant, and memorable trip.",
};

export const items = [
  {
    id: 1,
    title: "Everest Basecamp - 8000",
    groupSize: "2-14 pax",
    elevation: "up to 8,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    Activity: "Trekking",
    Grade: "moderate",
    GradeDescribe:
      "This category of treks requires basics outdoor experience and a certain degree of physical aptitude.  If you are physically fit and are the kind of person who enjoys the outdoors, age is not going to be an issue although it would be unwise for very young children to attempt these treks.",
    image: image1,
    country: "Nepal",
    season: "Spring/Autumn",
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    description_i:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched.",
    Itinerary: [
      "Day 01: Arrive in Kathmandu.",
      "      Day 02 – Stay in Kathmandu for official procedures and other preparations.",
      "Day 03 – Fly to Nepalgunj over night stay in hotel",
      "Day 04 – Fly to Juphal. (2,475m)",
      "Day 05 – Trek to Sulighat. (2,282m)",
      "Day 06 – Trek to Chhepka. (2,838m)",
      "Day 07 – Trek to Chhepka. (2,838m)",
      "Day 08 – Trek to Chhepka. (2,838m)",
      "Day 09 – Trek to Chhepka. (2,838m)",
      "Day 10 – Trek to Chhepka. (2,838m)",
      "Day 11 – Trek to Chhepka. (2,838m)",
      "Day 12 – Trek to Chhepka. (2,838m)",
      "Day 13 – Trek to Chhepka. (2,838m)",
      "Day 14 – Trek to Chhepka. (2,838m)",
      "Day 15 – Trek to Chhepka. (2,838m)",
    ],
    Inclusions: [
      " 1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6:  Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
      "8: Trekking permit.",
      "9: National park fee.",
      "10: Oxygen cylinder with mask and regulator for emergency use only.",
      "11: Hotel reservation.",
      "12: Airport pick up and drop.",
      "13: Welcome and farewell dinner.",
      "14: Helicopter rescue service.",
      "15: First aid kit.",
    ],
    Exclusions: [
      "1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6: Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
    ],
    Prices: [
      "For 04 pax – 3,720 per/person.",
      "For 06 pax –  3,600 per/person.",
      "For 08 pax – 3,480 per/person.",
      "For 10 pax – 3,360 per/person.",
      "For 12 pax – 3,240 per/person.",
      "For 14 pax – 3,120 per/person.",
    ],
    trekkingImage: [image1, image2, image3, image4],
  },
  {
    id: 2,
    title: "Annapurna Basecamp",
    groupSize: "2-14 pax",
    elevation: "up to 7,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image4,
    Activity: "Trekking",
    Grade: "easy",
    GradeDescribe:
      "This category of treks can be undertaken by anyone from children to adults and first-timers. These treks would give you a wonderful opportunity to explore beautiful places with your family and add to your trove of treasured memories. Most of the treks of this category are cultural treks, village tours, and lodge treks with trials that have easily available accommodation and other facilities.",
    country: "Nepal",
    season: "Spring/Autumn",
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    description_i:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched.",
    Itinerary: [
      "Day 01: Arrive in Kathmandu.",
      "      Day 02 – Stay in Kathmandu for official procedures and other preparations.",
      "Day 03 – Fly to Nepalgunj over night stay in hotel",
      "Day 04 – Fly to Juphal. (2,475m)",
      "Day 05 – Trek to Sulighat. (2,282m)",
      "Day 06 – Trek to Chhepka. (2,838m)",
      "Day 07 – Trek to Chhepka. (2,838m)",
      "Day 08 – Trek to Chhepka. (2,838m)",
      "Day 09 – Trek to Chhepka. (2,838m)",
      "Day 10 – Trek to Chhepka. (2,838m)",
      "Day 11 – Trek to Chhepka. (2,838m)",
      "Day 12 – Trek to Chhepka. (2,838m)",
      "Day 13 – Trek to Chhepka. (2,838m)",
      "Day 14 – Trek to Chhepka. (2,838m)",
      "Day 15 – Trek to Chhepka. (2,838m)",
    ],
    Inclusions: [
      " 1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6:  Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
      "8: Trekking permit.",
      "9: National park fee.",
      "10: Oxygen cylinder with mask and regulator for emergency use only.",
      "11: Hotel reservation.",
      "12: Airport pick up and drop.",
      "13: Welcome and farewell dinner.",
      "14: Helicopter rescue service.",
      "15: First aid kit.",
    ],
    Exclusions: [
      "1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6: Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
    ],
    Prices: [
      "For 04 pax – 3,720 per/person.",
      "For 06 pax –  3,600 per/person.",
      "For 08 pax – 3,480 per/person.",
      "For 10 pax – 3,360 per/person.",
      "For 12 pax – 3,240 per/person.",
      "For 14 pax – 3,120 per/person.",
    ],
    trekkingImage: [image1, image2, image3, image4],
  },
  {
    id: 3,
    title: "Lukla Basecamp",
    groupSize: "2-14 pax",
    elevation: "up to 7,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image3,
    Activity: "Trekking",
    Grade: "Hard",
    GradeDescribe:
      "This category of treks is for those with a strong physique, a lot of outdoor experience, and a taste for extreme adventures. You have to be physically and psychologically prepared to survive in an extreme environment under pressure.",
    country: "Nepal",
    season: "Spring/Autumn",
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    description_i:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched.",
    Itinerary: [
      "Day 01: Arrive in Kathmandu.",
      "      Day 02 – Stay in Kathmandu for official procedures and other preparations.",
      "Day 03 – Fly to Nepalgunj over night stay in hotel",
      "Day 04 – Fly to Juphal. (2,475m)",
      "Day 05 – Trek to Sulighat. (2,282m)",
      "Day 06 – Trek to Chhepka. (2,838m)",
      "Day 07 – Trek to Chhepka. (2,838m)",
      "Day 08 – Trek to Chhepka. (2,838m)",
      "Day 09 – Trek to Chhepka. (2,838m)",
      "Day 10 – Trek to Chhepka. (2,838m)",
      "Day 11 – Trek to Chhepka. (2,838m)",
      "Day 12 – Trek to Chhepka. (2,838m)",
      "Day 13 – Trek to Chhepka. (2,838m)",
      "Day 14 – Trek to Chhepka. (2,838m)",
      "Day 15 – Trek to Chhepka. (2,838m)",
    ],
    Inclusions: [
      " 1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6:  Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
      "8: Trekking permit.",
      "9: National park fee.",
      "10: Oxygen cylinder with mask and regulator for emergency use only.",
      "11: Hotel reservation.",
      "12: Airport pick up and drop.",
      "13: Welcome and farewell dinner.",
      "14: Helicopter rescue service.",
      "15: First aid kit.",
    ],
    Exclusions: [
      "1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6: Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
    ],
    Prices: [
      "For 04 pax – 3,720 per/person.",
      "For 06 pax –  3,600 per/person.",
      "For 08 pax – 3,480 per/person.",
      "For 10 pax – 3,360 per/person.",
      "For 12 pax – 3,240 per/person.",
      "For 14 pax – 3,120 per/person.",
    ],
    trekkingImage: [image1, image2, image3, image4],
  },
  {
    id: 4,
    title: "Lake Side Pokhara",
    groupSize: "2-14 pax",
    elevation: "up to 4,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image4,
    Activity: "Trekking",
    Grade: "Hard",
    country: "Nepal",
    season: "Spring/Autumn",
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    description_i:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched.",
    Itinerary: [
      "Day 01: Arrive in Kathmandu.",
      "      Day 02 – Stay in Kathmandu for official procedures and other preparations.",
      "Day 03 – Fly to Nepalgunj over night stay in hotel",
      "Day 04 – Fly to Juphal. (2,475m)",
      "Day 05 – Trek to Sulighat. (2,282m)",
      "Day 06 – Trek to Chhepka. (2,838m)",
      "Day 07 – Trek to Chhepka. (2,838m)",
      "Day 08 – Trek to Chhepka. (2,838m)",
      "Day 09 – Trek to Chhepka. (2,838m)",
      "Day 10 – Trek to Chhepka. (2,838m)",
      "Day 11 – Trek to Chhepka. (2,838m)",
      "Day 12 – Trek to Chhepka. (2,838m)",
      "Day 13 – Trek to Chhepka. (2,838m)",
      "Day 14 – Trek to Chhepka. (2,838m)",
      "Day 15 – Trek to Chhepka. (2,838m)",
    ],
    Inclusions: [
      " 1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6:  Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
      "8: Trekking permit.",
      "9: National park fee.",
      "10: Oxygen cylinder with mask and regulator for emergency use only.",
      "11: Hotel reservation.",
      "12: Airport pick up and drop.",
      "13: Welcome and farewell dinner.",
      "14: Helicopter rescue service.",
      "15: First aid kit.",
    ],
    Exclusions: [
      "1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6: Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
    ],
    Prices: [
      "For 04 pax – 3,720 per/person.",
      "For 06 pax –  3,600 per/person.",
      "For 08 pax – 3,480 per/person.",
      "For 10 pax – 3,360 per/person.",
      "For 12 pax – 3,240 per/person.",
      "For 14 pax – 3,120 per/person.",
    ],
    trekkingImage: [image1, image2, image3, image4],
  },
  {
    id: 5,
    title: "ISLAND PEAK (6,160M)",
    type: "Peaks",
    groupSize: "2-14 pax",
    elevation: "up to 4,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image1,
    Activity: "Trekking",
    Grade: "Hard",
    country: "Nepal",
    season: "Spring/Autumn",
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    description_i:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched.",
    Itinerary: [
      "Day 01: Arrive in Kathmandu.",
      "      Day 02 – Stay in Kathmandu for official procedures and other preparations.",
      "Day 03 – Fly to Nepalgunj over night stay in hotel",
      "Day 04 – Fly to Juphal. (2,475m)",
      "Day 05 – Trek to Sulighat. (2,282m)",
      "Day 06 – Trek to Chhepka. (2,838m)",
      "Day 07 – Trek to Chhepka. (2,838m)",
      "Day 08 – Trek to Chhepka. (2,838m)",
      "Day 09 – Trek to Chhepka. (2,838m)",
      "Day 10 – Trek to Chhepka. (2,838m)",
      "Day 11 – Trek to Chhepka. (2,838m)",
      "Day 12 – Trek to Chhepka. (2,838m)",
      "Day 13 – Trek to Chhepka. (2,838m)",
      "Day 14 – Trek to Chhepka. (2,838m)",
      "Day 15 – Trek to Chhepka. (2,838m)",
    ],
    Inclusions: [
      " 1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6:  Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
      "8: Trekking permit.",
      "9: National park fee.",
      "10: Oxygen cylinder with mask and regulator for emergency use only.",
      "11: Hotel reservation.",
      "12: Airport pick up and drop.",
      "13: Welcome and farewell dinner.",
      "14: Helicopter rescue service.",
      "15: First aid kit.",
    ],
    Exclusions: [
      "1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6: Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
    ],
    Prices: [
      "For 04 pax – 3,720 per/person.",
      "For 06 pax –  3,600 per/person.",
      "For 08 pax – 3,480 per/person.",
      "For 10 pax – 3,360 per/person.",
      "For 12 pax – 3,240 per/person.",
      "For 14 pax – 3,120 per/person.",
    ],
    trekkingImage: [image1, image2, image3, image4],
  },
  {
    id: 6,
    title: "ISLAND PEAK (6,160M)",
    type: "Peaks",
    groupSize: "2-14 pax",
    elevation: "up to 4,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image1,
    Activity: "Trekking",
    Grade: "Hard",
    country: "Nepal",
    season: "Spring/Autumn",
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    description_i:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched.",
    Itinerary: [
      "Day 01: Arrive in Kathmandu.",
      "      Day 02 – Stay in Kathmandu for official procedures and other preparations.",
      "Day 03 – Fly to Nepalgunj over night stay in hotel",
      "Day 04 – Fly to Juphal. (2,475m)",
      "Day 05 – Trek to Sulighat. (2,282m)",
      "Day 06 – Trek to Chhepka. (2,838m)",
      "Day 07 – Trek to Chhepka. (2,838m)",
      "Day 08 – Trek to Chhepka. (2,838m)",
      "Day 09 – Trek to Chhepka. (2,838m)",
      "Day 10 – Trek to Chhepka. (2,838m)",
      "Day 11 – Trek to Chhepka. (2,838m)",
      "Day 12 – Trek to Chhepka. (2,838m)",
      "Day 13 – Trek to Chhepka. (2,838m)",
      "Day 14 – Trek to Chhepka. (2,838m)",
      "Day 15 – Trek to Chhepka. (2,838m)",
    ],
    Inclusions: [
      " 1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6:  Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
      "8: Trekking permit.",
      "9: National park fee.",
      "10: Oxygen cylinder with mask and regulator for emergency use only.",
      "11: Hotel reservation.",
      "12: Airport pick up and drop.",
      "13: Welcome and farewell dinner.",
      "14: Helicopter rescue service.",
      "15: First aid kit.",
    ],
    Exclusions: [
      "1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6: Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
    ],
    Prices: [
      "For 04 pax – 3,720 per/person.",
      "For 06 pax –  3,600 per/person.",
      "For 08 pax – 3,480 per/person.",
      "For 10 pax – 3,360 per/person.",
      "For 12 pax – 3,240 per/person.",
      "For 14 pax – 3,120 per/person.",
    ],
    trekkingImage: [image1, image2, image3, image4],
  },
  {
    id: 7,
    title: "ISLAND PEAK (6,160M)",
    type: "Peaks",
    groupSize: "2-14 pax",
    elevation: "up to 4,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image1,
    Activity: "Trekking",
    Grade: "Hard",
    country: "Nepal",
    season: "Spring/Autumn",
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    description_i:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched.",
    Itinerary: [
      "Day 01: Arrive in Kathmandu.",
      "      Day 02 – Stay in Kathmandu for official procedures and other preparations.",
      "Day 03 – Fly to Nepalgunj over night stay in hotel",
      "Day 04 – Fly to Juphal. (2,475m)",
      "Day 05 – Trek to Sulighat. (2,282m)",
      "Day 06 – Trek to Chhepka. (2,838m)",
      "Day 07 – Trek to Chhepka. (2,838m)",
      "Day 08 – Trek to Chhepka. (2,838m)",
      "Day 09 – Trek to Chhepka. (2,838m)",
      "Day 10 – Trek to Chhepka. (2,838m)",
      "Day 11 – Trek to Chhepka. (2,838m)",
      "Day 12 – Trek to Chhepka. (2,838m)",
      "Day 13 – Trek to Chhepka. (2,838m)",
      "Day 14 – Trek to Chhepka. (2,838m)",
      "Day 15 – Trek to Chhepka. (2,838m)",
    ],
    Inclusions: [
      " 1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6:  Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
      "8: Trekking permit.",
      "9: National park fee.",
      "10: Oxygen cylinder with mask and regulator for emergency use only.",
      "11: Hotel reservation.",
      "12: Airport pick up and drop.",
      "13: Welcome and farewell dinner.",
      "14: Helicopter rescue service.",
      "15: First aid kit.",
    ],
    Exclusions: [
      "1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6: Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
    ],
    Prices: [
      "For 04 pax – 3,720 per/person.",
      "For 06 pax –  3,600 per/person.",
      "For 08 pax – 3,480 per/person.",
      "For 10 pax – 3,360 per/person.",
      "For 12 pax – 3,240 per/person.",
      "For 14 pax – 3,120 per/person.",
    ],
    trekkingImage: [image1, image2, image3, image4],
  },
  {
    id: 8,
    title: "ISLAND PEAK (6,160M)",
    type: "Peaks",
    groupSize: "2-14 pax",
    elevation: "up to 4,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image1,
    Activity: "Trekking",
    Grade: "Hard",
    country: "Nepal",
    season: "Spring/Autumn",
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    description_i:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched.",
    Itinerary: [
      "Day 01: Arrive in Kathmandu.",
      "      Day 02 – Stay in Kathmandu for official procedures and other preparations.",
      "Day 03 – Fly to Nepalgunj over night stay in hotel",
      "Day 04 – Fly to Juphal. (2,475m)",
      "Day 05 – Trek to Sulighat. (2,282m)",
      "Day 06 – Trek to Chhepka. (2,838m)",
      "Day 07 – Trek to Chhepka. (2,838m)",
      "Day 08 – Trek to Chhepka. (2,838m)",
      "Day 09 – Trek to Chhepka. (2,838m)",
      "Day 10 – Trek to Chhepka. (2,838m)",
      "Day 11 – Trek to Chhepka. (2,838m)",
      "Day 12 – Trek to Chhepka. (2,838m)",
      "Day 13 – Trek to Chhepka. (2,838m)",
      "Day 14 – Trek to Chhepka. (2,838m)",
      "Day 15 – Trek to Chhepka. (2,838m)",
    ],
    Inclusions: [
      " 1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6:  Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
      "8: Trekking permit.",
      "9: National park fee.",
      "10: Oxygen cylinder with mask and regulator for emergency use only.",
      "11: Hotel reservation.",
      "12: Airport pick up and drop.",
      "13: Welcome and farewell dinner.",
      "14: Helicopter rescue service.",
      "15: First aid kit.",
    ],
    Exclusions: [
      "1: Full board camping service for whole trekking period.",
      "2: Guide and camping staff.",
      "3: Cook and kitchen staff.",
      "4: Porters with best possible equipment.",
      "5: All staff and porters’ insurance.",
      "6: Domestic flight as in the itinerary.",
      "7: All ground transportation as in the itinerary.",
    ],
    Prices: [
      "For 04 pax – 3,720 per/person.",
      "For 06 pax –  3,600 per/person.",
      "For 08 pax – 3,480 per/person.",
      "For 10 pax – 3,360 per/person.",
      "For 12 pax – 3,240 per/person.",
      "For 14 pax – 3,120 per/person.",
    ],
    trekkingImage: [image1, image2, image3, image4],
  },
];

export const reviews = [
  {
    id: 1,
    name: "Shiva Giri",
    title: "Best Company to go trekking ",
    description:
      "We’re always pleased and confident in our recommendation of Iceland Trekking. Iceland Trekking has guided us since 1990 on seven outstanding treks to different regions of Nepal. Iceland Trekking’s guides and support team are knowledgeable, competent, resourceful, and demonstrate constant attention to hygiene and safety. Their extensive network of guides ensures a high degree of local knowledge, no matter which regions or peaks you chose. The equipment provided by Iceland Trekking is excellent. The food served daily is tasty, abundant, varied, nutritious, and often beautifully presented. Whether in a group of 2 or 12 clients, Iceland Trekking provides a high level of Professionalism at an amazingly low cost. We highly recommend Iceland Trekking for a wonderful trekking holiday in Nepal.",
    profile: image1,
  },
  {
    id: 2,
    name: "Nirmal Thing",
    title: "Best Company to go trekking in 2022",
    description:
      "After witnessing the increasing security risks on my mountain expeditions in Pakistan I decided to return to the safe haven of Nepal in 2011. By chance I ended up with an Iceland Trekking and Expeditions team on Himlung (Australian short cut route) that year. Service and price were so rewarding that I’m turning back every Autumn to discover another part of gorgeous Nepal guided by Tendy’s team. Strong porters, experienced climbing sherpas, cooks making delicious pizzas at 5000 meters high make every trip an unforgettable experience. Meeting Tendy at Kathmandu’s airport is like coming home ever since. I got to know Iceland’s manager as a clever person who can give you excellent advice to work out a tailor-made program off the beaten track but also as a pleasant humorous chap. In case events might take a different turn and you have to cope with unexpected problems during your trip, what is not uncommon on adventurous travels in a mountain region like the Himalayas with all its complexities, Tendy has the knowledge, flexibility and experience to find a quick solution meeting up with the expectations of his clients.",
    profile: image2,
  },
  {
    id: 3,
    name: "Lalit Mahato",
    title: "Best Company to go trekking 2023",
    description:
      "Meine Empfehlung für Himalaya-Einsteiger und auch Fortgeschrittene:Ich fahre seit 35 Jahren in den Himalaya. Ich habe dabei – wie auch in anderen Ländern dieser Welt – die Erfahrung gewonnen, dass es sehr wichtig ist, in fremden Ländern einen Menschen oder eine Agentur seines Vertrauens zu haben. Tendy Sherpa mit seiner kleinen, verlässlichen Agentur „Iceland Expeditions and Trekkings“ in Kathmandu gehört zu dieser sehr feinen Kategorie von Institutionen. Ich war mit Gruppen oder auch alleine auf vielen hohen Bergen, aber auch auf Trekkings mit „Iceland Expeditions“ bisher seit 25 Jahren unterwegs (insgesamt 50mal in Nepal), und habe mich immer eingebettet und in Sicherheit gefühlt, ",
    profile: image3,
  },
  {
    id: 4,
    name: "Ramesh Uncle",
    title: "Best Company to go trekking 2024",
    description:
      "We’re always pleased and confident in our recommendation of Iceland Trekking. Iceland Trekking has guided us since 1990 on seven outstanding treks to different regions of Nepal. Iceland Trekking’s guides and support team are knowledgeable, competent, resourceful, and demonstrate constant attention to hygiene and safety. Their extensive network of guides ensures a high degree of local knowledge, no matter which regions or peaks you chose. The equipment provided by Iceland Trekking is excellent. The food served daily is tasty, abundant, varied, nutritious, and often beautifully presented. Whether in a group of 2 or 12 clients, Iceland Trekking provides a high level of Professionalism at an amazingly low cost. We highly recommend Iceland Trekking for a wonderful trekking holiday in Nepal.",
    profile: image4,
  },
];

export const donation = {
  id: 1,
  image: donation_pic,
  title: "Social Responsibility",
  description:
    "We have been also supporting disabled and homeless children for the last 17 years (Disabled and Rehabilitation Center) with the cooperation of Sponsor Trek Nepal. Social responsibility is an ethical theory in which individuals are accountable for fulfilling their civic duty, and the actions of an individual must benefit the whole of society. In this way, there must be a balance between economic growth and the welfare of society and the environment. If this equilibrium is maintained, then social responsibility is accomplished.",
};

export const whyus = [
  {
    id: 1,
    image: choose1,
    title: "Safety",
    description:
      "The mountains are not only beautiful, but also formidable. We do not take safety of clients and staff lightly. We ensure that our equipment is up to date, our staff are all well-trained and familiar with safety procedures, and we plan ahead for all potential contingencies and make sure that we are covered. Rest assured that you are in very safe hands during your trip.",
  },
  {
    id: 2,
    image: choose2,
    title: "Experienced Staff",
    description:
      "Most of our staff have been in business for decades. They are well-trained and skilled professionals who have worked in many successful mountain expeditions and peak climbs to Everest, Cho Oyu, Dhaulagiri, Shisapangma, Lhotse, Kanchanjunga, Baruntse, Annapurna IV, Himlung, and Puthahiuchuli to name a few. They have worked with a very diverse and international clientele, including but not limited to clients from Europe, America, Canada, and Japan. This gives them unique insight and the ability to work with people from all over the world.",
  },
  {
    id: 3,
    image: choose3,
    title: "Competitive Pricing",
    description:
      "Iceland Trekking and Expedition organizes almost every aspect of any trek or expeditions Having been in the business as long as we have, we have been able to find the best people, equipment, and resources for the cheapest price possible. This means that we can provide competitive rates and make sure that you get the most out of your money.",
  },
  {
    id: 4,
    image: choose4,
    title: "Organized",
    description:
      "Expeditions and treks are a massive undertaking, where a small misstep can have extreme consequences. We recognize this and ensure that all our expeditions, treks, and peak climbs are meticulously planned and prepared for. Every day is accounted for, every person knows their specific role, and contingency plans for every potential event is laid out. This does not mean that expeditions with Iceland is a strict, rigid affair. Our staff know how to balance fun with work, and will make sure that you enjoy the trip to the fullest.",
  },
  {
    id: 5,
    image: choose5,
    title: "Responsible",
    description:
      "We take the responsibility of taking our clients to the summit of the world very seriously. We recognize that our clients have entrusted with us their time, their money, and even their lives. We want to make sure that we just not only do justice to this trust, but perform our responsibilities with honesty, integrity, and dedication.",
  },
  {
    id: 6,
    image: choose3,
    title: "Budget",
    description:
      "We take the responsibility of taking our clients to the summit of the world very seriously. We recognize that our clients have entrusted with us their time, their money, and even their lives. We want to make sure that we just not only do justice to this trust, but perform our responsibilities with honesty, integrity, and dedication.",
  },
];
