import image1 from "./src/image1.jpg";
import image2 from "./src/image2.jpg";
import image3 from "./src/image3.jpg";
import image4 from "./src/image4.jpg";
import team from "./src/team.jpg";
import donation_pic from "./src/donation.jpg";

export const slider = [
  {
    id: 1,
    image: image1,
    title: "Everest Base Camp",
    quote:
      "We provide services regarding mountain expedition, peak climbing, camping and lodge trekking or any kind of activities related with this field.",
  },
  {
    id: 2,
    image: image2,
    title: "Let us help you to make your trip better",
    quote:
      "We provide services regarding mountain expedition, peak climbing, camping and lodge trekking or any kind of activities related with this field.",
  },
  {
    id: 3,
    image: image3,
    title: "Let's go to the top of the world together",
    quote:
      "We provide services regarding mountain expedition, peak climbing, camping and lodge trekking or any kind of activities related with this field.",
  },
  {
    id: 4,
    image: image4,
    title: "We Can do everything for you - Trekking, Tours and so on.",
    quote:
      "We provide services regarding mountain expedition, peak climbing, camping and lodge trekking or any kind of activities related with this field.",
  },
];

export const aboutCompany = {
  id: 1,
  image: image1,
  title: "Namaste and warm greetings from Iceland Trekking & Expedition",
  description:
    "Iceland Trekking & Expedition (P) ltd. wishes you all good health, happiness, and strength to overcome this unprecedented time of the global pandemic.We have organized Mt. Everest expedition and Mt. Lhotse expedition in spring 2021. Likewise Mera peak, Labuche peak, and Island peak expeditions were all completed successfully in 2021 but, due to the unfortunate occurrence of the second wave of the pandemic during the spring season of 2021, Mt. Everest and Mt. Lhotse expeditions had to be stopped even though all the climbing members had completed the acclimatization process.",
  descriptionSecond:
    "After the second wave subsided, we have organized the Manaslu expedition, Dhaulagiri vii expedition, and Amadablam expedition successfully, in autumn 2021. Mera peak expedition was successfully organized and accomplished in the end of autumn 2021.All expeditions, treks, and tours including the international Everest expedition will continue operating in spring 2022.We want to assure all our trekking & expedition clients, that Iceland Trekking and Expedition is prepared to start all regular activities in upcoming 2022. We hope that the ongoing pandemic will overcome through a collective global effort. Despite all uncertainty and anxiety that every one of us are facing, we remain firm in the belief that hope must be kept alive. Stay safe and healthy.",
};

export const aboutTeam = {
  id: 1,
  image: team,
  title: "About Team",
  description:
    "After more than fifteen years of experience in trekking and mountain expedition, Tendy Sherpa founded Iceland Trekking & Expedition in 1994 as a company that provided services on tours, trekking, and mountain expedition in Nepal, Bhutan, Tibet, and Pakistan.We provide the best camping equipment, fresh and hygienic foods. Our staffs are leading experts in their field with each of them having decades of experience. Each member of our team is determined and dedicated to make sure that you have a pleasant, and memorable trip.",
};

export const items = [
  {
    id: 1,
    title: "Everest Basecamp",
    groupSize: "2-14 pax",
    elevation: "up to 4,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image1,
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    Itinerary: [
      {
        day1: "Arrive in Kathmandu.",
        day2: "Stay in Kathmandu for official and other preparations.",
        day3: "Kathmandu to Bhadrapur by air and drive to Phidim.",
        day4: " Drive to Taplejung.",
        day5: "Trek to Mitlung. (921m)",
        day6: " Trek to Chiruwa. (1,270m)",
        day7: "Trek to Sakarthum. (1,640m)",
        day8: "Trek to Amjilasa. (2,490m)",
        day9: "Trek to Gyabla. (2,730m)",
        day10: "Trek to Gunsa. (3,595m)",
        day11: "Rest day",
        day12: "Arrive in Kathmandu.",
        day13: "Stay in Kathmandu for official and other preparations.",
        day14: "Kathmandu to Bhadrapur by air and drive to Phidim.",
        day15: " Drive to Taplejung.",
        day16: "Trek to Mitlung. (921m)",
        day17: " Trek to Chiruwa. (1,270m)",
        day18: "Trek to Sakarthum. (1,640m)",
        day19: "Trek to Amjilasa. (2,490m)",
        day20: "Trek to Gyabla. (2,730m)",
        day21: "Trek to Gunsa. (3,595m)",
        day22: "Rest day",
      },
    ],
    Inclusions: [
      {
        1: "Full board camping service for whole trekking period.",
        2: "Guide and camping staff.",
        3: "Cook and kitchen staff.",
        4: "Porters with best possible equipment.",
        5: "All staff and porters’ insurance.",
        6: " Domestic flight as in the itinerary.",
        7: "All ground transportation as in the itinerary.",
        8: "Trekking permit.",
        9: "National park fee.",
        10: "Oxygen cylinder with mask and regulator for emergency use only.",
        11: "Hotel reservation.",
        12: "Airport pick up and drop.",
        13: "Welcome and farewell dinner.",
        14: "Helicopter rescue service.",
        15: "First aid kit.",
      },
    ],
    Exclusions: [
      {
        1: "Full board camping service for whole trekking period.",
        2: "Guide and camping staff.",
        3: "Cook and kitchen staff.",
        4: "Porters with best possible equipment.",
        5: "All staff and porters’ insurance.",
        6: " Domestic flight as in the itinerary.",
        7: "All ground transportation as in the itinerary.",
      },
    ],
  },
  {
    id: 2,
    title: "Annapurna Basecamp",
    groupSize: "2-14 pax",
    elevation: "up to 4,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image4,
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    Itinerary: [
      {
        day1: "Arrive in Kathmandu.",
        day2: "Stay in Kathmandu for official and other preparations.",
        day3: "Kathmandu to Bhadrapur by air and drive to Phidim.",
        day4: " Drive to Taplejung.",
        day5: "Trek to Mitlung. (921m)",
        day6: " Trek to Chiruwa. (1,270m)",
        day7: "Trek to Sakarthum. (1,640m)",
        day8: "Trek to Amjilasa. (2,490m)",
        day9: "Trek to Gyabla. (2,730m)",
        day10: "Trek to Gunsa. (3,595m)",
        day11: "Rest day",
        day12: "Arrive in Kathmandu.",
        day13: "Stay in Kathmandu for official and other preparations.",
        day14: "Kathmandu to Bhadrapur by air and drive to Phidim.",
        day15: " Drive to Taplejung.",
        day16: "Trek to Mitlung. (921m)",
        day17: " Trek to Chiruwa. (1,270m)",
        day18: "Trek to Sakarthum. (1,640m)",
        day19: "Trek to Amjilasa. (2,490m)",
        day20: "Trek to Gyabla. (2,730m)",
        day21: "Trek to Gunsa. (3,595m)",
        day22: "Rest day",
      },
    ],
    Inclusions: [
      {
        1: "Full board camping service for whole trekking period.",
        2: "Guide and camping staff.",
        3: "Cook and kitchen staff.",
        4: "Porters with best possible equipment.",
        5: "All staff and porters’ insurance.",
        6: " Domestic flight as in the itinerary.",
        7: "All ground transportation as in the itinerary.",
        8: "Trekking permit.",
        9: "National park fee.",
        10: "Oxygen cylinder with mask and regulator for emergency use only.",
        11: "Hotel reservation.",
        12: "Airport pick up and drop.",
        13: "Welcome and farewell dinner.",
        14: "Helicopter rescue service.",
        15: "First aid kit.",
      },
    ],
    Exclusions: [
      {
        1: "Full board camping service for whole trekking period.",
        2: "Guide and camping staff.",
        3: "Cook and kitchen staff.",
        4: "Porters with best possible equipment.",
        5: "All staff and porters’ insurance.",
        6: " Domestic flight as in the itinerary.",
        7: "All ground transportation as in the itinerary.",
      },
    ],
  },
  {
    id: 3,
    title: "Lukla Basecamp",
    groupSize: "2-14 pax",
    elevation: "up to 4,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image3,
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",

    Itinerary: [
      {
        day1: "Arrive in Kathmandu.",
        day2: "Stay in Kathmandu for official and other preparations.",
        day3: "Kathmandu to Bhadrapur by air and drive to Phidim.",
        day4: " Drive to Taplejung.",
        day5: "Trek to Mitlung. (921m)",
        day6: " Trek to Chiruwa. (1,270m)",
        day7: "Trek to Sakarthum. (1,640m)",
        day8: "Trek to Amjilasa. (2,490m)",
        day9: "Trek to Gyabla. (2,730m)",
        day10: "Trek to Gunsa. (3,595m)",
        day11: "Rest day",
        day12: "Arrive in Kathmandu.",
        day13: "Stay in Kathmandu for official and other preparations.",
        day14: "Kathmandu to Bhadrapur by air and drive to Phidim.",
        day15: " Drive to Taplejung.",
        day16: "Trek to Mitlung. (921m)",
        day17: " Trek to Chiruwa. (1,270m)",
        day18: "Trek to Sakarthum. (1,640m)",
        day19: "Trek to Amjilasa. (2,490m)",
        day20: "Trek to Gyabla. (2,730m)",
        day21: "Trek to Gunsa. (3,595m)",
        day22: "Rest day",
      },
    ],
    Inclusions: [
      {
        1: "Full board camping service for whole trekking period.",
        2: "Guide and camping staff.",
        3: "Cook and kitchen staff.",
        4: "Porters with best possible equipment.",
        5: "All staff and porters’ insurance.",
        6: " Domestic flight as in the itinerary.",
        7: "All ground transportation as in the itinerary.",
        8: "Trekking permit.",
        9: "National park fee.",
        10: "Oxygen cylinder with mask and regulator for emergency use only.",
        11: "Hotel reservation.",
        12: "Airport pick up and drop.",
        13: "Welcome and farewell dinner.",
        14: "Helicopter rescue service.",
        15: "First aid kit.",
      },
    ],
    Exclusions: [
      {
        1: "Full board camping service for whole trekking period.",
        2: "Guide and camping staff.",
        3: "Cook and kitchen staff.",
        4: "Porters with best possible equipment.",
        5: "All staff and porters’ insurance.",
        6: " Domestic flight as in the itinerary.",
        7: "All ground transportation as in the itinerary.",
      },
    ],
  },
  {
    id: 4,
    title: "Lake Side Pokhara",
    groupSize: "2-14 pax",
    elevation: "up to 4,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image4,
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    Itinerary: [
      {
        day1: "Arrive in Kathmandu.",
        day2: "Stay in Kathmandu for official and other preparations.",
        day3: "Kathmandu to Bhadrapur by air and drive to Phidim.",
        day4: " Drive to Taplejung.",
        day5: "Trek to Mitlung. (921m)",
        day6: " Trek to Chiruwa. (1,270m)",
        day7: "Trek to Sakarthum. (1,640m)",
        day8: "Trek to Amjilasa. (2,490m)",
        day9: "Trek to Gyabla. (2,730m)",
        day10: "Trek to Gunsa. (3,595m)",
        day11: "Rest day",
        day12: "Arrive in Kathmandu.",
        day13: "Stay in Kathmandu for official and other preparations.",
        day14: "Kathmandu to Bhadrapur by air and drive to Phidim.",
        day15: " Drive to Taplejung.",
        day16: "Trek to Mitlung. (921m)",
        day17: " Trek to Chiruwa. (1,270m)",
        day18: "Trek to Sakarthum. (1,640m)",
        day19: "Trek to Amjilasa. (2,490m)",
        day20: "Trek to Gyabla. (2,730m)",
        day21: "Trek to Gunsa. (3,595m)",
        day22: "Rest day",
      },
    ],
    Inclusions: [
      {
        1: "Full board camping service for whole trekking period.",
        2: "Guide and camping staff.",
        3: "Cook and kitchen staff.",
        4: "Porters with best possible equipment.",
        5: "All staff and porters’ insurance.",
        6: " Domestic flight as in the itinerary.",
        7: "All ground transportation as in the itinerary.",
        8: "Trekking permit.",
        9: "National park fee.",
        10: "Oxygen cylinder with mask and regulator for emergency use only.",
        11: "Hotel reservation.",
        12: "Airport pick up and drop.",
        13: "Welcome and farewell dinner.",
        14: "Helicopter rescue service.",
        15: "First aid kit.",
      },
    ],
    Exclusions: [
      {
        1: "Full board camping service for whole trekking period.",
        2: "Guide and camping staff.",
        3: "Cook and kitchen staff.",
        4: "Porters with best possible equipment.",
        5: "All staff and porters’ insurance.",
        6: " Domestic flight as in the itinerary.",
        7: "All ground transportation as in the itinerary.",
      },
    ],
  },
  {
    id: 5,
    title: "Kanchenjunga Basecamp",
    groupSize: "2-14 pax",
    elevation: "up to 4,790m",
    startFrom: "Departs from Kathmandu, Nepal",
    starton: "11th April 2022",
    image: image1,
    description:
      "Kanchenjunga is the world’s third-highest mountain at a height of 8586m, located in the Eastern part of Nepal. Four glaciers radiate from the peak, pointing roughly to the north-east, south-east, north-west and south-west. It is surrounded by the Kanchenjunga Conservation Area that keeps the wilderness and natural beauty of the region protected and untouched. This region is the habitat for rare species such as the majestic Snow Leopard, the reclusive Himalayan Black Bear, the Blue Sheep, the Musk Deer and the Assamese Macaque to name a few. Some of the richest rhododendron forests are found here, where there are over 2000 species of flowering plants recorded and many new species still being discovered.Local habitations are few and scattered, but the locals that you meet will give you a fascinating insight into the existing cultural diversity in Nepal. They are friendly, hospitable people and are always willing to help trekkers that pass their way.",
    Itinerary: [
      {
        day1: "Arrive in Kathmandu.",
        day2: "Stay in Kathmandu for official and other preparations.",
        day3: "Kathmandu to Bhadrapur by air and drive to Phidim.",
        day4: " Drive to Taplejung.",
        day5: "Trek to Mitlung. (921m)",
        day6: " Trek to Chiruwa. (1,270m)",
        day7: "Trek to Sakarthum. (1,640m)",
        day8: "Trek to Amjilasa. (2,490m)",
        day9: "Trek to Gyabla. (2,730m)",
        day10: "Trek to Gunsa. (3,595m)",
        day11: "Rest day",
        day12: "Arrive in Kathmandu.",
        day13: "Stay in Kathmandu for official and other preparations.",
        day14: "Kathmandu to Bhadrapur by air and drive to Phidim.",
        day15: " Drive to Taplejung.",
        day16: "Trek to Mitlung. (921m)",
        day17: " Trek to Chiruwa. (1,270m)",
        day18: "Trek to Sakarthum. (1,640m)",
        day19: "Trek to Amjilasa. (2,490m)",
        day20: "Trek to Gyabla. (2,730m)",
        day21: "Trek to Gunsa. (3,595m)",
        day22: "Rest day",
      },
    ],
    Inclusions: [
      {
        1: "Full board camping service for whole trekking period.",
        2: "Guide and camping staff.",
        3: "Cook and kitchen staff.",
        4: "Porters with best possible equipment.",
        5: "All staff and porters’ insurance.",
        6: " Domestic flight as in the itinerary.",
        7: "All ground transportation as in the itinerary.",
        8: "Trekking permit.",
        9: "National park fee.",
        10: "Oxygen cylinder with mask and regulator for emergency use only.",
        11: "Hotel reservation.",
        12: "Airport pick up and drop.",
        13: "Welcome and farewell dinner.",
        14: "Helicopter rescue service.",
        15: "First aid kit.",
      },
    ],
    Exclusions: [
      {
        1: "Full board camping service for whole trekking period.",
        2: "Guide and camping staff.",
        3: "Cook and kitchen staff.",
        4: "Porters with best possible equipment.",
        5: "All staff and porters’ insurance.",
        6: " Domestic flight as in the itinerary.",
        7: "All ground transportation as in the itinerary.",
      },
    ],
  },
];

export const reviews = [
  {
    id: 1,
    name: "Shiva Giri",
    title: "Best Company to go trekking ",
    description:
      "We’re always pleased and confident in our recommendation of Iceland Trekking. Iceland Trekking has guided us since 1990 on seven outstanding treks to different regions of Nepal. Iceland Trekking’s guides and support team are knowledgeable, competent, resourceful, and demonstrate constant attention to hygiene and safety. Their extensive network of guides ensures a high degree of local knowledge, no matter which regions or peaks you chose. The equipment provided by Iceland Trekking is excellent. The food served daily is tasty, abundant, varied, nutritious, and often beautifully presented. Whether in a group of 2 or 12 clients, Iceland Trekking provides a high level of Professionalism at an amazingly low cost. We highly recommend Iceland Trekking for a wonderful trekking holiday in Nepal.",
    profile: image1,
  },
  {
    id: 2,
    name: "Nirmal Thing",
    title: "Best Company to go trekking in 2022",
    description:
      "After witnessing the increasing security risks on my mountain expeditions in Pakistan I decided to return to the safe haven of Nepal in 2011. By chance I ended up with an Iceland Trekking and Expeditions team on Himlung (Australian short cut route) that year. Service and price were so rewarding that I’m turning back every Autumn to discover another part of gorgeous Nepal guided by Tendy’s team. Strong porters, experienced climbing sherpas, cooks making delicious pizzas at 5000 meters high make every trip an unforgettable experience. Meeting Tendy at Kathmandu’s airport is like coming home ever since. I got to know Iceland’s manager as a clever person who can give you excellent advice to work out a tailor-made program off the beaten track but also as a pleasant humorous chap. In case events might take a different turn and you have to cope with unexpected problems during your trip, what is not uncommon on adventurous travels in a mountain region like the Himalayas with all its complexities, Tendy has the knowledge, flexibility and experience to find a quick solution meeting up with the expectations of his clients.",
    profile: image2,
  },
  {
    id: 3,
    name: "Lalit Mahato",
    title: "Best Company to go trekking 2023",
    description:
      "Meine Empfehlung für Himalaya-Einsteiger und auch Fortgeschrittene:Ich fahre seit 35 Jahren in den Himalaya. Ich habe dabei – wie auch in anderen Ländern dieser Welt – die Erfahrung gewonnen, dass es sehr wichtig ist, in fremden Ländern einen Menschen oder eine Agentur seines Vertrauens zu haben. Tendy Sherpa mit seiner kleinen, verlässlichen Agentur „Iceland Expeditions and Trekkings“ in Kathmandu gehört zu dieser sehr feinen Kategorie von Institutionen. Ich war mit Gruppen oder auch alleine auf vielen hohen Bergen, aber auch auf Trekkings mit „Iceland Expeditions“ bisher seit 25 Jahren unterwegs (insgesamt 50mal in Nepal), und habe mich immer eingebettet und in Sicherheit gefühlt, ",
    profile: image3,
  },
  {
    id: 4,
    name: "Ramesh Uncle",
    title: "Best Company to go trekking 2024",
    description:
      "We’re always pleased and confident in our recommendation of Iceland Trekking. Iceland Trekking has guided us since 1990 on seven outstanding treks to different regions of Nepal. Iceland Trekking’s guides and support team are knowledgeable, competent, resourceful, and demonstrate constant attention to hygiene and safety. Their extensive network of guides ensures a high degree of local knowledge, no matter which regions or peaks you chose. The equipment provided by Iceland Trekking is excellent. The food served daily is tasty, abundant, varied, nutritious, and often beautifully presented. Whether in a group of 2 or 12 clients, Iceland Trekking provides a high level of Professionalism at an amazingly low cost. We highly recommend Iceland Trekking for a wonderful trekking holiday in Nepal.",
    profile: image4,
  },
];

export const donation = {
  id: 1,
  image: donation_pic,
  title: "Social Responsibility",
  description:
    "We have been also supporting disabled and homeless children for the last 17 years (Disabled and Rehabilitation Center) with the cooperation of Sponsor Trek Nepal. Social responsibility is an ethical theory in which individuals are accountable for fulfilling their civic duty, and the actions of an individual must benefit the whole of society. In this way, there must be a balance between economic growth and the welfare of society and the environment. If this equilibrium is maintained, then social responsibility is accomplished.",
};
